### ISSUE TITLE
Can't run it 

### ISSUE THREAD

**Issue by qcol** [doogie2301/pinup-popper-browser#1]
Hi

Can't run it:
![image](https://user-images.githubusercontent.com/358993/84039108-111a8180-a9a1-11ea-9b2f-5e45e53bc11e.png)

Tried to install better-sqlite3 but no luck... so, I want to try "Running without Node" but can't find PinUpBrowser.zip file (PinUpBrowser.exe). Where can i find it?

**Comment by doogie2301** [comment]
you ran "npm install" first?  the standalone version can be accessed from the Releases tab, here is the latest: https://github.com/doogie2301/pinup-popper-browser/releases/tag/v0.1.2

**Comment by qcol** [comment]
yes, of course ran npm install before... something with sqlite.  OK, downloaded exe and it works now. Thank You - a great way to display the menu. I've been waiting for a long time for such a way :)
